server:
  port: 8300

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.200.138:3306/lab_website
    username: root
    password: 
  servlet:
    multipart:
      enabled: true

aliyun:
  oss:
    endpoint: 
    accessKeyId: 
    accessKeySecret: 
    bucketName: 
    policy:
      expire: 300
    maxSize: 10
    callback: 
    dir:
      prefix: 

jwt:
  secret: 123123123
  expiration: 1000


